import cacheJson from "./sample-cache.json";
import { cacheKey } from "./cache-key";
import type { Analysis, LanguageId } from "./types";

/**
 * Pre-computed Jev results for the built-in playground samples, generated by
 * `scripts/build-sample-cache.ts` against the real API. Sample code never
 * changes, so an exact-content match returns instantly with no API call, no
 * rate-limit token spent. Any edit to the snippet misses the cache and falls
 * through to the live endpoint.
 */
const CACHE = cacheJson as unknown as Record<string, Analysis>;

export function cachedAnalysis(
  language: LanguageId,
  code: string,
): Analysis | null {
  return CACHE[cacheKey(language, code)] ?? null;
}
